const charDefinitions = [
    [undefined, "Кінець"],
    [undefined, "Початок"],
    [undefined, "Передвказівка"],

    ['\n', "Міжряд"],

    ['[', "Відкрита квадратна дужка", `<div class="kd-icon"><svg class="no-dark-shadow" width="2" height="7" viewBox="0 0 2 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="5" fill="currentColor"/><rect width="2" height="1" fill="currentColor"/><rect y="6" width="2" height="1" fill="currentColor"/></svg></div>`],
    ['{', "Відкрита фігурна дужка", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="1" width="1" height="2" fill="currentColor"/><rect x="1" y="4" width="1" height="2" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['(', "Відкрита дужка", `<div class="kd-icon"><svg class="no-dark-shadow" width="2" height="7" viewBox="0 0 2 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="5" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['<', "Менше", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="3" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],

    ['§', "Секція", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['#', "Мітка", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['@', "Адреса", `<div class="kd-icon"><svg class="no-dark-shadow" width="6" height="7" viewBox="0 0 6 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="5" y="2" width="1" height="1" fill="currentColor"/><rect x="5" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['№', "Номер", `<div class="kd-icon"><svg class="no-dark-shadow" width="7" height="7" viewBox="0 0 7 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="5" width="1" height="1" fill="currentColor"/><rect x="5" y="2" width="1" height="1" fill="currentColor"/><rect x="6" y="1" width="1" height="1" fill="currentColor"/><rect x="5" y="4" width="1" height="1" fill="currentColor"/><rect x="6" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['+', "Хрестик", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="3" viewBox="0 0 3 3" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['₴', "Гривня", `<div class="kd-icon"><svg class="no-dark-shadow" width="6" height="7" viewBox="0 0 6 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="5" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    [undefined, "Дія", `<div class="kd-icon"><svg class="no-dark-shadow" width="7" height="7" viewBox="0 0 7 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="6" y="3" width="1" height="1" fill="currentColor"/><rect x="5" y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    [undefined, "Енергія", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/></svg></div>`],

    ['0', "Нуль", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['1', "Один", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['2', "Два", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['3', "Три", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/></svg></div>`],
    ['4', "Чотири", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['5', "Пʼять", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['6', "Шість", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['7', "Сім", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['8', "Вісім", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><path d="M2 5H3V6H2V5Z" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['9', "Девʼять", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/></svg></div>`],

    ['\'', "Лапка", `<div class="kd-icon"><svg class="no-dark-shadow" width="1" height="2" viewBox="0 0 1 2" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['"', "Дволапка", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="2" viewBox="0 0 3 2" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['`', "Косолапка", `<div class="kd-icon"><svg class="no-dark-shadow" width="2" height="2" viewBox="0 0 2 2" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['_', "Підриска", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="1" viewBox="0 0 5 1" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['-', "Риска", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="1" viewBox="0 0 3 1" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['ʼ', "Апостроф", `<div class="kd-icon"><svg class="no-dark-shadow" width="2" height="2" viewBox="0 0 2 2" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/></svg></div>`],

    ['А', "Велика буква \"А\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Б', "Велика буква \"Б\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['В', "Велика буква \"В\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Г', "Велика буква \"Г\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Д', "Велика буква \"Д\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Е', "Велика буква \"Е\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Є', "Велика буква \"Є\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ж', "Велика буква \"Ж\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/></svg></div>`],
    ['З', "Велика буква \"З\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['И', "Велика буква \"И\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['І', "Велика буква \"І\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="7" viewBox="0 0 3 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ї', "Велика буква \"Ї\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="3" height="9" viewBox="0 0 3 9" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="7" width="1" height="1" fill="currentColor"/><rect x="1" y="8" width="1" height="1" fill="currentColor"/><rect y="8" width="1" height="1" fill="currentColor"/><rect x="2" y="8" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Й', "Велика буква \"Й\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="9" viewBox="0 0 4 9" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="2" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="7" width="1" height="1" fill="currentColor"/><rect y="8" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="8" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="7" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['К', "Велика буква \"К\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Л', "Велика буква \"Л\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['М', "Велика буква \"М\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Н', "Велика буква \"Н\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['О', "Велика буква \"О\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['П', "Велика буква \"П\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Р', "Велика буква \"Р\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['С', "Велика буква \"С\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Т', "Велика буква \"Т\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['У', "Велика буква \"У\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ф', "Велика буква \"Ф\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Х', "Велика буква \"Х\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="1" y="2" width="1" height="1" fill="currentColor"/><path d="M0 5H1V6H0V5Z" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="4" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ц', "Велика буква \"Ц\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg"><rect y="1" width="1" height="1" fill="currentColor"/><rect width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="7" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ч', "Велика буква \"Ч\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ш', "Велика буква \"Ш\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Щ', "Велика буква \"Щ\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="6" height="8" viewBox="0 0 6 8" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="4" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="6" width="1" height="1" fill="currentColor"/><rect x="5" y="7" width="1" height="1" fill="currentColor"/><rect x="5" y="6" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ь', "Велика буква \"Ь\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Ю', "Велика буква \"Ю\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="5" height="7" viewBox="0 0 5 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1" fill="currentColor"/><rect y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="2" width="1" height="1" fill="currentColor"/><rect x="2" y="1" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/><rect x="4" y="1" width="1" height="1" fill="currentColor"/><rect x="4" y="2" width="1" height="1" fill="currentColor"/><rect x="4" y="3" width="1" height="1" fill="currentColor"/><rect x="4" y="4" width="1" height="1" fill="currentColor"/><rect x="4" y="5" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="2" y="5" width="1" height="1" fill="currentColor"/><rect x="2" y="4" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['Я', "Велика буква \"Я\"", `<div class="kd-icon"><svg class="no-dark-shadow" width="4" height="7" viewBox="0 0 4 7" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" width="1" height="1" fill="currentColor"/><rect y="1" width="1" height="1" fill="currentColor"/><rect x="2" width="1" height="1" fill="currentColor"/><rect x="3" y="1" width="1" height="1" fill="currentColor"/><rect x="3" y="2" width="1" height="1" fill="currentColor"/><rect x="3" y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="5" width="1" height="1" fill="currentColor"/><rect y="2" width="1" height="1" fill="currentColor"/><rect x="1" y="3" width="1" height="1" fill="currentColor"/><rect x="2" y="3" width="1" height="1" fill="currentColor"/><rect y="4" width="1" height="1" fill="currentColor"/><rect y="5" width="1" height="1" fill="currentColor"/><rect y="6" width="1" height="1" fill="currentColor"/><rect x="3" y="4" width="1" height="1" fill="currentColor"/><rect x="3" y="3" width="1" height="1" fill="currentColor"/><rect x="3" width="1" height="1" fill="currentColor"/></svg></div>`],
    ['а', "Мала буква \"а\""],
    ['б', "Мала буква \"б\""],
    ['в', "Мала буква \"в\""],
    ['г', "Мала буква \"г\""],
    ['д', "Мала буква \"д\""],
    ['е', "Мала буква \"е\""],
    ['є', "Мала буква \"є\""],
    ['ж', "Мала буква \"ж\""],
    ['з', "Мала буква \"з\""],
    ['и', "Мала буква \"и\""],
    ['і', "Мала буква \"і\""],
    ['ї', "Мала буква \"ї\""],
    ['й', "Мала буква \"й\""],
    ['к', "Мала буква \"к\""],
    ['л', "Мала буква \"л\""],
    ['м', "Мала буква \"м\""],
    ['н', "Мала буква \"н\""],
    ['о', "Мала буква \"о\""],
    ['п', "Мала буква \"п\""],
    ['р', "Мала буква \"р\""],
    ['с', "Мала буква \"с\""],
    ['т', "Мала буква \"т\""],
    ['у', "Мала буква \"у\""],
    ['ф', "Мала буква \"ф\""],
    ['х', "Мала буква \"х\""],
    ['ц', "Мала буква \"ц\""],
    ['ч', "Мала буква \"ч\""],
    ['ш', "Мала буква \"ш\""],
    ['щ', "Мала буква \"щ\""],
    ['ь', "Мала буква \"ь\""],
    ['ю', "Мала буква \"ю\""],
    ['я', "Мала буква \"я\""],

    ['Ґ', "Велика буква \"Ґ\""],
    ['Ё', "Велика буква \"ё\""],
    ['Ъ', "Велика буква \"ъ\""],
    ['Ы', "Велика буква \"ы\""],
    ['Э', "Велика буква \"э\""],
    ['ґ', "Мала буква \"ґ\""],
    ['ё', "Мала буква \"ё\""],
    ['ъ', "Мала буква \"ъ\""],
    ['ы', "Мала буква \"ы\""],
    ['э', "Мала буква \"э\""],

    [',', "Кома"],
    [':', "Двокрапка"],
    [';', "Крапкакома"],
    ['.', "Крапка"],
    ['?', "Питання"],
    ['!', "Оклик"],

    ['$', "Долар"],
    ['%', "Відсоток"],
    ['°', "Градус"],
    ['*', "Зірочка"],
    ['/', "Коса"],
    ['|', "Пряма"],
    ['\\', "Обернена коса"],
    ['&', "Амперсанд"],
    ['^', "Пірамідка"],
    ['~', "Тильда"],
    ['=', "Рівно"],

    ['>', "Більше"],
    [')', "Закрита дужка"],
    ['}', "Закрита фігурна дужка"],
    [']', "Закрита квадратна дужка"],

    [' ', "Пропуск"],
];

const textEncoder = new TextEncoder();

const lines = charDefinitions.map(([char, definition, logo], index) => {
    const columns = [];
    columns.push(definition);
    if (logo) {
        columns.push(logo);
    } else if (char) {
        columns.push(char[0].replaceAll('\n', '').replaceAll('\\', '\\\\').replaceAll('>', '\\>').replaceAll('<', '\\<').replaceAll('[', '\\[').replaceAll('|', '\\|'));
    } else {
        columns.push('');
    }
    columns.push(String(index));
    columns.push(`<small>0ш</small>${index.toString(16).toUpperCase().replaceAll('A', 'А').replaceAll('B', 'Б').replaceAll('C', 'В').replaceAll('D', 'Г').replaceAll('E', 'Д').replaceAll('F', 'Е')}`);
    columns.push(`<small>0д</small>${index.toString(2)}`);
    if (char) {
        let value = String(char[0].charCodeAt(0));
        const encoded = textEncoder.encode(char[0]);
        if (encoded.length > 1) {
            value = `${value} <small>\\[${encoded.map((c) => c).join(', ')}]</small>`;
        }
        columns.push(value);
    } else {
        columns.push('');
    }
    return `|${columns.join(' | ')}|`;
});

const table = lines.join('\n');
console.log(table);

// const charset = charDefinitions.map(([char]) => char[0]).filter((char) => char && char !== '\n').join('');
// console.log(charset);